CREATE TABLE work_role (
                           role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           title VARCHAR(50) NOT NULL,
                           description VARCHAR(50) NOT NULL,
                           salary DOUBLE NOT NULL,
                           creation_date DATE NOT NULL
);
select * from WORK_ROLE;
